name: explore
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"
dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dartx: ^1.2.0
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  get_it: ^7.6.4
  hive: ^2.2.3
  path_provider: ^2.1.1
  equatable: ^2.0.5
  skeletonizer: ^1.4.2
  http: ^1.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_flavorizr: ^2.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
