# Use the official Node.js Alpine image as the base
FROM node:18-alpine

# Create a directory for our application
WORKDIR /

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the port the application uses
EXPOSE 3165

# Run the application when the container starts
CMD ["node", "index.js"]
